version: '3.8'

services:
  # Frontend with serve
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:8080/api/v1
    restart: unless-stopped
    
  # Frontend with nginx (alternative)
  frontend-nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles:
      - nginx

networks:
  default:
    name: frontend-network